"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useParams, useRouter } from "next/navigation";
import dynamic from "next/dynamic";
import { motion, AnimatePresence } from "framer-motion";
import {
  Play,
  CheckCircle,
  XCircle,
  Clock,
  AlertTriangle,
  Loader2,
  RefreshCw,
  Database,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
} from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import ProblemPanel from "@/components/interview/problem-panel";
import OutputPanel from "@/components/interview/output-panel";
import { useAuth } from "@/hooks/use-auth";
import { useCodeExecution } from "@/hooks/use-code-execution";
import {
  getInterviewSession,
  updateInterviewCode,
  updateInterviewStatus,
} from "@/lib/db";
import {
  LANGUAGE_CONFIG,
  type SupportedLanguage,
  type InterviewSession,
  type ChatMessage,
} from "@/types";
import { cn } from "@/lib/utils";

// Heavy components — no SSR
const CodeEditor = dynamic(
  () => import("@/components/interview/code-editor"),
  { ssr: false }
);
const TextEditor = dynamic(
  () => import("@/components/interview/text-editor"),
  { ssr: false }
);
const ChatPanel = dynamic(
  () => import("@/components/interview/chat-panel"),
  { ssr: false }
);

// ── helpers ──────────────────────────────────────────────────────────────────

const DIFFICULTY_STYLES: Record<string, string> = {
  easy: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
  medium: "bg-yellow-500/15 text-yellow-400 border-yellow-500/30",
  hard: "bg-red-500/15 text-red-400 border-red-500/30",
};

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60).toString().padStart(2, "0");
  const s = (seconds % 60).toString().padStart(2, "0");
  return `${m}:${s}`;
}

// New separator (generated by /api/interview/boilerplate)
const SQL_SPLIT_MARKER = "-- ========== YOUR QUERY BELOW ==========";
// Legacy separator kept for backward compat with older sessions
const SQL_SPLIT_MARKER_LEGACY = "-- YOUR QUERY BELOW";

function splitSqlCode(code: string): { schema: string; query: string } {
  for (const marker of [SQL_SPLIT_MARKER, SQL_SPLIT_MARKER_LEGACY]) {
    const idx = code.indexOf(marker);
    if (idx !== -1) {
      return {
        schema: code.slice(0, idx).trim(),
        query: code.slice(idx + marker.length).trim(),
      };
    }
  }
  return { schema: "", query: code };
}

// ── Schema parser + panel ─────────────────────────────────────────────────────

function parseSchema(
  schema: string
): { tableName: string; columns: { name: string; type: string }[] }[] {
  const tables: { tableName: string; columns: { name: string; type: string }[] }[] = [];
  const tableRe = /CREATE\s+TABLE\s+(\w+)\s*\(([\s\S]*?)\);/gi;
  let m: RegExpExecArray | null;
  while ((m = tableRe.exec(schema)) !== null) {
    const tableName = m[1];
    const columns = m[2]
      .split(",")
      .map((c) => c.trim())
      .filter((c) => {
        const up = c.toUpperCase();
        return (
          c &&
          !up.startsWith("PRIMARY KEY") &&
          !up.startsWith("FOREIGN KEY") &&
          !up.startsWith("UNIQUE") &&
          !up.startsWith("CHECK")
        );
      })
      .map((c) => {
        const parts = c.trim().split(/\s+/);
        return {
          name: parts[0] ?? "",
          type: (parts[1] ?? "TEXT").replace(/[(),]/g, ""),
        };
      })
      .filter((col) => col.name);
    tables.push({ tableName, columns });
  }
  return tables;
}

function SchemaPanel({ schema }: { schema: string }) {
  const tables = parseSchema(schema);
  return (
    <div className="h-full overflow-y-auto p-3 space-y-3">
      {tables.length === 0 ? (
        <p className="text-xs text-muted-foreground p-2">No schema loaded.</p>
      ) : (
        tables.map(({ tableName, columns }) => (
          <div
            key={tableName}
            className="glass rounded-lg border border-white/10 overflow-hidden"
          >
            <div className="px-3 py-2 border-b border-white/10 bg-white/5 flex items-center gap-2">
              <Database className="w-3 h-3 text-blue-400 shrink-0" />
              <span className="text-xs font-mono font-semibold text-blue-400">
                {tableName}
              </span>
              <span className="text-xs text-muted-foreground ml-auto">
                {columns.length} col{columns.length !== 1 ? "s" : ""}
              </span>
            </div>
            <div className="divide-y divide-white/5">
              {columns.map(({ name, type }) => (
                <div key={name} className="flex items-center justify-between px-3 py-1.5">
                  <span className="text-xs font-mono text-foreground/80">{name}</span>
                  <span className="text-xs font-mono text-muted-foreground">{type}</span>
                </div>
              ))}
            </div>
          </div>
        ))
      )}
    </div>
  );
}

// ── Evaluating overlay ────────────────────────────────────────────────────────

function EvaluatingOverlay() {
  const MESSAGES = [
    "Analyzing your solution…",
    "Reviewing code quality…",
    "Assessing problem-solving approach…",
    "Preparing detailed feedback…",
  ];
  const [msgIdx, setMsgIdx] = useState(0);

  useEffect(() => {
    const id = setInterval(
      () => setMsgIdx((i) => (i + 1) % MESSAGES.length),
      2200
    );
    return () => clearInterval(id);
  }, []);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-60 bg-background/95 backdrop-blur-sm flex flex-col items-center justify-center gap-6"
    >
      {/* Pulsing ring */}
      <div className="relative">
        <motion.div
          animate={{ scale: [1, 1.15, 1], opacity: [0.4, 0.1, 0.4] }}
          transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
          className="absolute inset-0 rounded-full bg-blue-500/20"
        />
        <div className="relative w-16 h-16 rounded-full bg-blue-500/10 border border-blue-500/30 flex items-center justify-center">
          <Loader2 className="w-7 h-7 text-blue-400 animate-spin" />
        </div>
      </div>

      <div className="text-center space-y-2">
        <p className="text-base font-semibold">AI is evaluating your solution</p>
        <AnimatePresence mode="wait">
          <motion.p
            key={msgIdx}
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -6 }}
            transition={{ duration: 0.3 }}
            className="text-sm text-muted-foreground"
          >
            {MESSAGES[msgIdx]}
          </motion.p>
        </AnimatePresence>
      </div>
    </motion.div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function InterviewSessionPage() {
  const params = useParams<{ sessionId: string }>();
  const sessionId = params?.sessionId ?? "";
  const router = useRouter();
  const { user } = useAuth();

  // Session
  const [session, setSession] = useState<InterviewSession | null>(null);
  const [loading, setLoading] = useState(true);

  // Editor
  const [code, setCode] = useState("");
  const [sqlSchema, setSqlSchema] = useState("");
  const [selectedLanguage, setSelectedLanguage] =
    useState<SupportedLanguage>("python");

  // Chat
  const [messages, setMessages] = useState<ChatMessage[]>([]);

  // Timer
  const [elapsed, setElapsed] = useState(0);
  const timerWarnedRef = useRef(false);

  // Auto-save
  const autoSaveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const lastSavedCodeRef = useRef("");
  // Original boilerplate for reset
  const originalCodeRef = useRef("");

  // Dialog + evaluation state
  const [showSubmitDialog, setShowSubmitDialog] = useState(false);
  const [showEndDialog, setShowEndDialog] = useState(false);
  const [showResetDialog, setShowResetDialog] = useState(false);
  const [isEvaluating, setIsEvaluating] = useState(false);

  // Code execution
  const { execute, isRunning, result, reset } = useCodeExecution();

  // ── beforeunload warning ────────────────────────────────────────────────────

  useEffect(() => {
    if (loading || !session || isEvaluating) return;
    const handler = (e: BeforeUnloadEvent) => {
      e.preventDefault();
      e.returnValue = "You have an interview in progress.";
    };
    window.addEventListener("beforeunload", handler);
    return () => window.removeEventListener("beforeunload", handler);
  }, [loading, session, isEvaluating]);

  // ── Load session ────────────────────────────────────────────────────────────

  useEffect(() => {
    if (!sessionId || !user) return;

    async function load() {
      const s = await getInterviewSession(sessionId);
      if (!s || s.userId !== user!.uid) {
        toast.error("Session not found. Please start a new interview.");
        router.replace("/interview");
        return;
      }
      // If already completed, go straight to feedback
      if (s.status === "completed" && s.feedback) {
        router.replace(`/interview/${sessionId}/feedback`);
        return;
      }
      setSession(s);
      setSelectedLanguage((s.language as SupportedLanguage) ?? "python");
      setMessages(s.messages ?? []);

      if (s.language === "sql") {
        const { schema, query } = splitSqlCode(s.code ?? "");
        setSqlSchema(schema);
        setCode(query);
        originalCodeRef.current = query;
      } else {
        setCode(s.code ?? "");
        originalCodeRef.current = s.code ?? "";
      }
      setLoading(false);
    }

    load().catch((err) => {
      console.error(err);
      setLoading(false);
      toast.error("Failed to load interview session.");
    });
  }, [sessionId, user, router]);

  // ── Timer ───────────────────────────────────────────────────────────────────

  useEffect(() => {
    if (!session) return;
    const startMs =
      session.startedAt instanceof Date
        ? session.startedAt.getTime()
        : (session.startedAt as unknown as { seconds: number }).seconds * 1000;
    const initial = Math.floor((Date.now() - startMs) / 1000);
    setElapsed(Math.max(0, initial));

    const id = setInterval(() => {
      setElapsed((prev) => {
        const next = prev + 1;
        if (
          !timerWarnedRef.current &&
          session.maxDurationMinutes > 0 &&
          next >= session.maxDurationMinutes * 60
        ) {
          timerWarnedRef.current = true;
          toast.warning("Time's up! You can submit now or continue.", {
            duration: 8000,
          });
        }
        return next;
      });
    }, 1000);

    return () => clearInterval(id);
  }, [session]);

  // ── Auto-save ───────────────────────────────────────────────────────────────

  const scheduleAutoSave = useCallback(
    (newCode: string) => {
      if (autoSaveTimerRef.current) clearTimeout(autoSaveTimerRef.current);
      autoSaveTimerRef.current = setTimeout(async () => {
        if (newCode === lastSavedCodeRef.current) return;
        lastSavedCodeRef.current = newCode;
        const full =
          selectedLanguage === "sql" && sqlSchema
            ? `${sqlSchema}\n${SQL_SPLIT_MARKER}\n${newCode}`
            : newCode;
        try {
          await updateInterviewCode(sessionId, full);
        } catch {
          // swallow silently
        }
      }, 30_000);
    },
    [sessionId, selectedLanguage, sqlSchema]
  );

  const handleCodeChange = useCallback((val: string) => {
    setCode(val);
    scheduleAutoSave(val);
    reset();
  }, [scheduleAutoSave, reset]);

  // ── Language change ─────────────────────────────────────────────────────────

  function handleLanguageChange(lang: SupportedLanguage) {
    setSelectedLanguage(lang);
    if (lang === "sql") setSqlSchema("");
  }

  // ── Reset to boilerplate ────────────────────────────────────────────────────

  function handleResetToBoilerplate() {
    setCode(originalCodeRef.current);
    setShowResetDialog(false);
    reset();
  }

  // ── Reset SQL database ───────────────────────────────────────────────────────

  async function handleResetDatabase() {
    const { resetSqlDatabase } = await import("@/lib/sql-executor");
    resetSqlDatabase();
    reset();
    toast.success("Database reset — will reinitialize on next run.");
  }

  // ── Run code ────────────────────────────────────────────────────────────────

  function handleRun() {
    if (selectedLanguage === "sql") {
      execute(code, "sql", sqlSchema || undefined);
    } else {
      execute(code, selectedLanguage);
    }
  }

  // ── Submit (with evaluation) ─────────────────────────────────────────────────

  async function handleSubmitConfirm() {
    if (!session || !user) return;
    setShowSubmitDialog(false);
    setIsEvaluating(true);

    // Save latest code before evaluating
    const fullCode =
      selectedLanguage === "sql" && sqlSchema
        ? `${sqlSchema}\n${SQL_SPLIT_MARKER}\n${code}`
        : code;

    try {
      await updateInterviewCode(sessionId, fullCode);
    } catch {
      // non-fatal
    }

    try {
      const res = await fetch("/api/interview/evaluate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sessionId,
          code: fullCode,
          interviewType: session.type,
          problem: session.problem,
          conversationHistory: messages.map((m) => ({
            role: m.role,
            content: m.content,
          })),
          userId: user.uid,
        }),
      });

      if (res.status === 401) {
        router.push("/login");
        return;
      }
      if (res.status === 429) {
        throw new Error("Limit reached. Upgrade for more access.");
      }
      if (!res.ok) {
        const err = (await res.json().catch(() => ({}))) as { error?: string };
        throw new Error(err.error ?? `Evaluation failed (${res.status})`);
      }

      router.push(`/interview/${sessionId}/feedback`);
    } catch (err) {
      setIsEvaluating(false);
      const msg = err instanceof Error ? err.message : "Evaluation failed. Please try again.";
      if (msg.includes("Limit reached")) {
        toast.error(msg, {
          action: { label: "Upgrade", onClick: () => router.push("/settings") },
        });
      } else {
        toast.error(msg);
      }
    }
  }

  // ── End (abandon) ────────────────────────────────────────────────────────────

  async function handleEndConfirm() {
    if (!session) return;
    setShowEndDialog(false);
    try {
      await updateInterviewStatus(sessionId, "abandoned", {
        completedAt: new Date(),
      });
      router.push("/dashboard");
    } catch {
      toast.error("Failed to end session. Please try again.");
    }
  }

  // ── Derived ──────────────────────────────────────────────────────────────────

  const monacoId = LANGUAGE_CONFIG[selectedLanguage]?.monacoId ?? "plaintext";
  const isCoding = session?.type === "coding";
  const isOverTime =
    !!session &&
    session.maxDurationMinutes > 0 &&
    elapsed >= session.maxDurationMinutes * 60;

  // ── Loading ──────────────────────────────────────────────────────────────────

  if (loading) {
    return (
      <div className="fixed inset-0 z-50 bg-background flex items-center justify-center">
        <div className="flex flex-col items-center gap-3 text-muted-foreground">
          <div className="w-8 h-8 rounded-full border-2 border-white/20 border-t-blue-400 animate-spin" />
          <p className="text-sm">Loading interview…</p>
        </div>
      </div>
    );
  }

  if (!session) return null;

  // ── Render ────────────────────────────────────────────────────────────────────

  return (
    <>
      {/* Evaluating overlay */}
      <AnimatePresence>{isEvaluating && <EvaluatingOverlay />}</AnimatePresence>

      <div className="fixed inset-0 z-40 bg-background flex flex-col">
        {/* ── Header bar ── */}
        <header className="h-12 flex items-center gap-3 px-4 border-b border-white/10 bg-background/95 backdrop-blur-sm shrink-0">
          <div
            className={cn(
              "flex items-center gap-1.5 font-mono text-sm font-semibold tabular-nums",
              isOverTime ? "text-red-400" : "text-foreground"
            )}
          >
            {isOverTime ? (
              <AlertTriangle className="w-3.5 h-3.5" />
            ) : (
              <Clock className="w-3.5 h-3.5 text-muted-foreground" />
            )}
            {formatTime(elapsed)}
            {session.maxDurationMinutes > 0 && (
              <span className="text-muted-foreground font-normal text-xs">
                / {formatTime(session.maxDurationMinutes * 60)}
              </span>
            )}
          </div>

          <div className="w-px h-4 bg-white/10 mx-1" />

          <h1 className="text-sm font-semibold truncate flex-1 min-w-0">
            {session.problem.title}
          </h1>

          <Badge
            variant="outline"
            className={cn(
              "capitalize text-xs shrink-0 hidden sm:inline-flex",
              DIFFICULTY_STYLES[session.problem.difficulty]
            )}
          >
            {session.problem.difficulty}
          </Badge>

          <Button
            size="sm"
            variant="destructive"
            className="h-7 text-xs shrink-0"
            onClick={() => setShowEndDialog(true)}
            disabled={isEvaluating}
          >
            <XCircle className="w-3.5 h-3.5 mr-1" />
            End
          </Button>
        </header>

        {/* ── Split pane ── */}
        <div className="flex-1 flex overflow-hidden min-h-0">
          {/* Left: Problem + Chat */}
          <div className="w-1/2 flex flex-col border-r border-white/10 min-w-0 overflow-hidden">
            <Tabs defaultValue="problem" className="flex flex-col h-full">
              <div className="shrink-0 px-3 pt-2 border-b border-white/10">
                <TabsList variant="line" className="h-8">
                  <TabsTrigger value="problem" className="text-xs">
                    Problem
                  </TabsTrigger>
                  <TabsTrigger value="chat" className="text-xs">
                    Chat
                  </TabsTrigger>
                  {selectedLanguage === "sql" && sqlSchema && (
                    <TabsTrigger value="schema" className="text-xs">
                      Schema
                    </TabsTrigger>
                  )}
                </TabsList>
              </div>
              <TabsContent value="problem" className="flex-1 overflow-hidden mt-0">
                <ProblemPanel problem={session.problem} type={session.type} />
              </TabsContent>
              <TabsContent value="chat" className="flex-1 overflow-hidden mt-0">
                <ChatPanel
                  sessionId={sessionId}
                  messages={messages}
                  onMessagesChange={setMessages}
                  code={code}
                  interviewType={session.type}
                />
              </TabsContent>
              {selectedLanguage === "sql" && sqlSchema && (
                <TabsContent value="schema" className="flex-1 overflow-hidden mt-0">
                  <SchemaPanel schema={sqlSchema} />
                </TabsContent>
              )}
            </Tabs>
          </div>

          {/* Right: Code + Output or TextEditor */}
          <div className="w-1/2 flex flex-col min-w-0 overflow-hidden">
            {isCoding ? (
              <Tabs defaultValue="code" className="flex flex-col h-full">
                <div className="shrink-0 px-3 pt-2 border-b border-white/10">
                  <TabsList variant="line" className="h-8">
                    <TabsTrigger value="code" className="text-xs">
                      Code
                    </TabsTrigger>
                    <TabsTrigger value="output" className="text-xs">
                      Output
                      {result && (
                        <span
                          className={cn(
                            "ml-1 w-1.5 h-1.5 rounded-full inline-block",
                            result.status === "Success" ||
                              result.status === "Accepted"
                              ? "bg-emerald-400"
                              : "bg-red-400"
                          )}
                        />
                      )}
                    </TabsTrigger>
                  </TabsList>
                </div>
                <TabsContent
                  value="code"
                  className="flex-1 overflow-hidden mt-0"
                >
                  <CodeEditor
                    language={monacoId}
                    value={code}
                    onChange={handleCodeChange}
                    selectedLanguage={selectedLanguage}
                    onLanguageChange={handleLanguageChange}
                  />
                </TabsContent>
                <TabsContent
                  value="output"
                  className="flex-1 overflow-hidden mt-0"
                >
                  <OutputPanel result={result} isRunning={isRunning} />
                </TabsContent>
              </Tabs>
            ) : (
              <div className="flex flex-col h-full">
                <div className="shrink-0 px-4 py-2.5 border-b border-white/10">
                  <span className="text-xs text-muted-foreground font-medium">
                    Your Answer
                  </span>
                </div>
                <div className="flex-1 overflow-hidden">
                  <TextEditor value={code} onChange={handleCodeChange} />
                </div>
              </div>
            )}
          </div>
        </div>

        {/* ── Bottom action bar ── */}
        <footer className="h-12 shrink-0 flex items-center gap-3 px-4 border-t border-white/10 bg-background/95 backdrop-blur-sm">
          {isCoding ? (
            <>
              <Badge
                variant="outline"
                className="text-xs border-white/10 text-muted-foreground hidden sm:inline-flex"
              >
                {LANGUAGE_CONFIG[selectedLanguage]?.name}
              </Badge>

              <div className="flex-1" />

              {result && !isRunning && (
                <span
                  className={cn(
                    "text-xs font-medium",
                    result.status === "Success" || result.status === "Accepted"
                      ? "text-emerald-400"
                      : "text-red-400"
                  )}
                >
                  {result.status}
                </span>
              )}

              {originalCodeRef.current && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 text-xs gap-1.5 text-muted-foreground hover:text-foreground"
                  onClick={() => setShowResetDialog(true)}
                  disabled={isEvaluating}
                  title="Reset code to original boilerplate"
                >
                  <RefreshCw className="w-3.5 h-3.5" />
                  Reset
                </Button>
              )}

              {selectedLanguage === "sql" && sqlSchema && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 text-xs gap-1.5 text-muted-foreground hover:text-foreground"
                  onClick={handleResetDatabase}
                  disabled={isEvaluating}
                  title="Reset SQL database to original schema data"
                >
                  <Database className="w-3.5 h-3.5" />
                  Reset DB
                </Button>
              )}

              <Button
                variant="outline"
                size="sm"
                className="h-7 text-xs gap-1.5 border-white/15 hover:border-white/30"
                onClick={handleRun}
                disabled={isRunning || !code.trim() || isEvaluating}
              >
                {isRunning ? (
                  <span className="w-3.5 h-3.5 rounded-full border-2 border-white/30 border-t-white animate-spin" />
                ) : (
                  <Play className="w-3.5 h-3.5" />
                )}
                Run Code
              </Button>

              <Button
                size="sm"
                className="h-7 text-xs gap-1.5"
                onClick={() => setShowSubmitDialog(true)}
                disabled={isEvaluating}
              >
                <CheckCircle className="w-3.5 h-3.5" />
                Submit Solution
              </Button>
            </>
          ) : (
            <>
              <div className="flex-1" />
              <Button
                size="sm"
                className="h-7 text-xs gap-1.5"
                onClick={() => setShowSubmitDialog(true)}
                disabled={isEvaluating}
              >
                <CheckCircle className="w-3.5 h-3.5" />
                Submit Answer
              </Button>
            </>
          )}
        </footer>
      </div>

      {/* ── Submit confirmation dialog ── */}
      <Dialog open={showSubmitDialog} onOpenChange={setShowSubmitDialog}>
        <DialogContent showCloseButton={false}>
          <DialogHeader>
            <DialogTitle>Submit your solution?</DialogTitle>
            <DialogDescription>
              The AI will evaluate your{" "}
              {isCoding ? "code" : "answer"} and generate a detailed
              performance report with scores, feedback, and improvement tips.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setShowSubmitDialog(false)}
            >
              Keep Working
            </Button>
            <Button size="sm" onClick={handleSubmitConfirm} className="gap-2">
              <CheckCircle className="w-3.5 h-3.5" />
              Submit &amp; Evaluate
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── End interview dialog ── */}
      <Dialog open={showEndDialog} onOpenChange={setShowEndDialog}>
        <DialogContent showCloseButton={false}>
          <DialogHeader>
            <DialogTitle>End without submitting?</DialogTitle>
            <DialogDescription>
              Your progress will be saved, but no AI evaluation will be
              generated. You can still review the problem later from your
              dashboard.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setShowEndDialog(false)}
            >
              Continue Interview
            </Button>
            <Button
              size="sm"
              variant="destructive"
              onClick={handleEndConfirm}
            >
              End Interview
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Reset to boilerplate dialog ── */}
      <Dialog open={showResetDialog} onOpenChange={setShowResetDialog}>
        <DialogContent showCloseButton={false}>
          <DialogHeader>
            <DialogTitle>Reset code to boilerplate?</DialogTitle>
            <DialogDescription>
              Your current code will be replaced with the original starter
              template. This cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setShowResetDialog(false)}
            >
              Cancel
            </Button>
            <Button
              size="sm"
              variant="destructive"
              onClick={handleResetToBoilerplate}
              className="gap-2"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              Reset Code
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
